databases:
  - name: servidorJonathan
    plan: free
    databaseName: dbfutec
    user: jonathan

services:
  - type: web
    plan: free
    name: Futec
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Futec.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorJonathan
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: futec.onrender.com

# set DATABASE_URL=postgresql://jonathan:T0XmVjLvicibcC5nmd0TgbX5PZxQABpd@dpg-cqoqc1qj1k6c73d6l0k0-a.oregon-postgres.render.com/dbfutec