# Generated by Django 4.0.6 on 2024-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='producto')),
            ],
        ),
    ]
