# Generated by Django 4.0.6 on 2024-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
