# Generated by Django 4.0.6 on 2024-07-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('foto', models.FileField(blank=True, null=True, upload_to='clientes')),
            ],
        ),
    ]
