# Generated by Django 4.0.6 on 2024-07-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
