# Generated by Django 4.0.6 on 2024-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0007_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='linea_productos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='material',
            field=models.CharField(default='', max_length=100),
        ),
    ]
